server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    include: oauth
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 683045214580-p48885e4a29cpl2d01m4j02oa27hucd9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
